[package]
name = "typst-ucas-thesis"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["WenjieXuCN"]
license = "MIT"
description = "中国科学院大学学位论文模板。University of Chinese Academy of Sciences Thesis."
repository = "https://github.com/WenjieXuCN/typst-ucas-thesis"
keywords = ["University of Chinese Academy of Sciences", "UCAS", "thesis"]
categories = ["thesis"]
exclude = ["imgs"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"